ELISA_Immunoassay:
  - elisa
  - immunoassay
  - serology
  - biomarker
  - tsh
  - hemagglutination

Immunoprecipitation:
  - immunoprecipitation
  - magnetic_particle

Aptamer_Selection_SELEX:
  - selex
  - aptamer

Antimicrobial_Susceptibility_Testing:
  - mic_screen
  - antibiotic_mic
  - susceptibility

CRISPR_Based_Diagnostics:
  - cas13
  - crispr
  - carmen
  - isothermal_assay

PCR_NucleicAcid:
  - proxseq
  - seq
  - ngs
  - scrna
  - sequencing
  - genotyping
  - cloning
  - pcr
  - amplification
  - nucleic_acid
  - zika
  - rubella
  - denv
  - ddpcr
  - qpcr
  - magnetofluidic

Extraction_Purification:
  - extraction
  - purification
  - isolation
  - microfiltration
  - precipitation
  - monolith
  - depletion
  - spe

Cell_Based_Assay:
  - nfkb
  - organoid
  - coculture
  - microbiome
  - electroporation
  - transfection
  - ctc
  - cell_
  - apoptosis
  - cell_culture
  - caspase
  - macrophage
  - single_cell
  - immune

Small_Molecule_Drug:
  - ciprofloxacin
  - fentanyl
  - glucose
  - estradiol
  - heroin
  - diazepam
  - morphine
  - oxycodone
  - sorafenib
  - steroid
  - estrogen

Omics_Proteomics:
  - proteomic
  - proteomics
  - microproteomics
  - omics
  - metabolomics
  - oxidoreductase

Aerosol_Environmental:
  - aerosol
  - environmental
  - monitoring
  - sensing

Dilution:
  - dilution
  - titration

Phytochemical_Colorimetric_Assay:
  - flavonoid
  - anthocyanin
  - ascorbic_acid
  - dpph
  - phenolic
  - soluble_sugar
  - hydrogen_peroxide
  - lipid_peroxide

Clinical_Diagnostics_Newborn_Screening:
  - succinylacetone
  - newborn_screening
  - lysosomal_storage
  - physiological_fluids
  - hepatotoxicity
  - sars_cov2
  - diagnostic_test
  - explosive_detection
  - tnt

Enzyme_Kinetics_Screening:
  - enzyme_assay
  - ribozyme
  - enzyme_screening
  - enzymatic

Synthetic_Biology_Genetic_Engineering:
  - crispr
  - electroporation
  - electrotransformation
  - transfection
  - lentiviral
  - competent_cells
  - synbio
  - strain_development
  - transformation
  - mage
  - crispr_mage

Oncology_Cell_Pathology:
  - breast_cancer
  - deformability
  - bacteremia
  - malaria
  - ctc
  - liquid_biopsy
  - cluster

Device_Fabrication_Protocol_Formalization:
  - fabrication
  - ewod
  - microbioreactor
  - biology_protocols
  - reciprocating
  - evaporation_mgmt
  - world_to_chip
  - picoliter
  - multilayer_hybrid
  - droplet_on_tape
  - droplet_volume_measurement

RNA_Sequencing_Epigenomics:
  - mirna
  - proxseq
  - paired_tag
  - disc_dmf
  - digital_recovery
  - ev_mirna
  - ecl_mirna
  - methylome
  - bisulfite
  - methylation

Chemistry_Synthesis_Purification_MS:
  - fucosylation
  - glycosylation
  - desalination
  - concentrator
  - peptidomimetics
  - macrocycle
  - mass_spec
  - ief_cge
  - id2m
  - chemokine
  - lipid_screen
  - immunomodulator
  - isoclone
  - conjugation
  - entrap

Other: []
